import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

const state = {
  accent: '',
  chineseData: {
    loginSafe: '安全、私密、有保障！',
    loginInfo: '——冰塔数科云盘，Filecoin存储',
    loginTitle: 'FILECOIN存储系统',
    systemTitle: '开放平台',
    welcome: '欢迎登录',
    bindMobile: '绑定手机号',
    welcome2: '欢迎注册数据伙伴',
    loginMobile: '手机号',
    loginUserPlr: '请输入用户名',
    loginPassWorld: '请输入登录密码',
    loginButton: '登 录',
    loginSendCode: '短信已发送，请注意查收',
    outLogin: '退出登录',
    searchInput: '文件名搜索',
    selectTile: '筛选',
    upFile: '上传文件',
    fileRealName: '文件名',
    createDate: '时间',
    fileSize: '大小',
    statusName: '状态',
    action: '操作',
    copy: '复制哈希',
    noThing: '这里什么都没有🤷‍♀️',
    toUpFile: '快去上传文件吧！',
    toChuang: '去上传',
    selectStatus: '状态',
    selectTime: '时间',
    selectReset: '重置',
    selectSure: '确认',
    editorTile: '编辑',
    editorName: '文件名称',
    editorInputPlr: '请输入文件名称',
    editorCell: '取消',
    upBoxTitle: '拖动文件到此处或点击按钮上传',
    upBoxDown: '松手即可上传',
    upBoxCell: '已取消',
    upBoxLoading: '上传中',
    loadkyes: '加密中',
    upBoxSuccess: '上传成功',
    upBoxError: '上传失败',
    copyMessage: '已复制到粘贴板',
    copyNoneHas: '暂无哈希值',
    startTime: '开始时间',
    endTime: '结束时间',
    mobileLoginInof: '冰塔数科云盘，Filecoin存储',
    mobileLoginGotoLogin: '去登录',
    mobiledownload: '下载',
    requsetAgin: '出错啦，请稍后再试',
    noMore: '没有更多了',
    DealCIDName: '订单CID',
    loadingMore: '查看更多',
    noData: '没有更多了'
  },
  englishData: {
    loginSafe: 'Safety、Privacy、Security！',
    loginInfo: '——冰塔数科Cloud，Filecoin Storage',
    loginTitle: 'Welcome To 冰塔数科 Cloud！',
    loginMobile: 'Phone number',
    loginMobilePlr: 'Enter your mobile phone number',
    loginCode: 'Verification',
    loginCodePlr: 'Enter code',
    loginCodeSend: 'Send Code',
    loginCodeReflesh: 'Resend',
    loginButton: 'LOGIN',
    loginCurrentMobile: 'Please enter the correct mobile phone number',
    loginCurrentCode: 'Please enter the correct verification code',
    loginSendCode: 'SMS has been sent, please check',
    outLogin: 'Log out',
    searchInput: 'Search file name',
    selectTile: 'Filter',
    upFile: 'Upload Data',
    fileRealName: 'File Name',
    createDate: 'Time',
    fileSize: 'Size',
    statusName: 'State',
    action: 'Operation',
    copy: 'Copy CID',
    noThing: 'Nothing here🤷‍♀️',
    toUpFile: 'Go and upload the data!',
    toChuang: 'Upload Data',
    selectStatus: 'State',
    selectTime: 'Time',
    selectReset: 'Reset',
    selectSure: 'Confirm',
    editorTile: 'Edit',
    editorName: 'File Name',
    editorInputPlr: 'Secence_one',
    editorCell: 'Cancel',
    upBoxTitle: 'Click below or drop a file on the page to upload a file.',
    upBoxDown: 'Release and upload',
    upBoxCell: 'Cancel',
    upBoxLoading: 'Uploading…',
    upBoxSuccess: 'SUCCESS',
    upBoxError: 'ERROR',
    copyMessage: 'Copied to pasteboard',
    copyNoneHas: 'No hash value',
    startTime: 'start time',
    endTime: 'end time',
    mobileLoginInof: '冰塔数科Cloud，Filecoin Storage',
    mobileLoginGotoLogin: 'Sign in',
    mobiledownload: 'Download',
    requsetAgin: 'Something went wrong. Please try again later',
    noMore: 'No more',
    DealCIDName: 'Deal CID',
    loadingMore: 'More',
    noData: 'No More'
  }

}
export default new Vuex.Store({
  state
})
